# Snowflake credentials - UPDATE THESE WITH YOUR ACTUAL CREDENTIALS
SNOWFLAKE_ACCOUNT = "TBUIIKV-PD48737"
SNOWFLAKE_USER = "AYYAZAHMED"
SNOWFLAKE_PASSWORD = "VQ5JmjSXpMJATsb"  # ← PUT YOUR REAL PASSWORD HERE
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "SNOWFLAKE_SAMPLE_DATA"
SNOWFLAKE_SCHEMA = "TPCH_SF1000"