# .streamlit/secrets.toml
# This file is for Streamlit Cloud secrets

[snowflake]
account = "TBUIIKV-PD48737"
user = "AYYAZAHMED"
password = "VQ5JmjSXpMJATsb"
warehouse = "COMPUTE_WH"
database = "SNOWFLAKE_SAMPLE_DATA"
schema = "TPCH_SF1000"

[app]
secret_key = "9fc4ecbeb00e14bebcf6937a692221bdf37f4f9af0e752cceddd440ee1477980"
admin_email = "ayyazahmed@yahoo.com"